### ISSUE TITLE
Auto Reforge breaks multiple TModLoader methods for other mods

### ISSUE THREAD

**Issue by elytrafae** [SadOnion/AutoReforge#3]
Hi!

To cut it short, yes. This mod makes the `GlobalNPC.OnChatButtonClicked` and the `GlobalItem.CanReforge` hooks behave oddly.

`GlobalNPC.OnChatButtonClicked` does not get fired for the Goblin Tinkerer when the Reforge button is clicked.
Steps to reproduce:
1. Make a GlobalNPC with the following code inside:
```
public override bool AppliesToEntity(NPC entity, bool lateInstantiation) {
    return entity.type == NPCID.GoblinTinkerer;
}

public override void OnChatButtonClicked(NPC npc, bool firstButton) {
    if (!firstButton) { 
        npc.StrikeInstantKill();
    }
}
```
2. Load into the game
3. Talk to the Goblin Tinkerer and select Reforge.

If AutoReforge is enabled, the Goblin Tinkerer does not die. If it is disabled, he dies.

`GlobalItem.CanReforge` is completely ignored by the mod
Steps to reproduce:
1. Make a GlobalItem with the following code inside:
```
public override bool CanReforge(Item item) {
    return false;
}
```
2. Load into the game
3. Try to Reforge any item

If AutoReforge is enabled, the item gets Reforged. If it is disabled, nothing happens.

**Comment by SadOnion** [comment]
I tested it using the following:

- tModLoader v2024.6.3.1
- Terraria v1.4.4.9
- AutoReforge 2023.7.25
- TestMod with your code

Everything works fine on my end. Could you please double-check to ensure the issue isn't on your side?
